---
title: "10x PAH BMP9 - Integration"
author: "Yvon Mbouamboua<BR>mbouamboua@ipmc.cnrs.fr"
date: 'Compiled: `r Sys.Date()`'
#date: 'Compiled: `r format(Sys.Date(), "%d %B %Y")`'
output:
  rmdformats::readthedown:
    self-contained: yes
    highlight: haddock
    css: styles.css
    theme: flatly
    number_sections: yes
    thumbnails: no
  html_notebook:
    theme: cerulean #bootstrap #yeti, cerulean, cosmo, darkly, flatly, journal, lumen, paper,readable,sandstone,simplex,spacelab,united
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---


# Setting parameters

```{r setup, include=TRUE, warning=FALSE}

invisible(gc())
the.seed <- 1337L
options(future.globals.maxSize = 80000 * 1024^2)
workdir <- "/data/data_mbouamboua/projects/10x_htap_bmp9"
outdir <-  paste(workdir, "output", sep = "/")
data <-  paste(outdir, "samples", sep = "/")
source("/data/data_mbouamboua/apps/Rpkgs/Rpkgs.R")
source("/data/data_mbouamboua/apps/4743/utilities.R")
set.seed(the.seed)

```


# Integrating samples by condition

## Integration CTRL (A1, B1, C1, D1, E1)

```{r }

A1 <- readRDS(paste(data, "A1.rds", sep = "/"))
B1 <- readRDS(paste(data, "B1.rds", sep = "/"))
C1 <- readRDS(paste(data, "C1.rds", sep = "/"))
D1 <- readRDS(paste(data, "D1.rds", sep = "/"))
E1 <- readRDS(paste(data, "E1.rds", sep = "/"))
list <- c(A1, B1, C1, D1, E1)
rm(A1, B1, C1, D1, E1)
invisible(gc())

features <- SelectIntegrationFeatures(object.list = list, nfeatures = 3000)
list <- PrepSCTIntegration(object.list = list, anchor.features = features)
list <- lapply(X = list, FUN = RunPCA, verbose = FALSE, features = features)
anchors <- FindIntegrationAnchors(object.list = list, anchor.features = features, 
                                  normalization.method = "SCT", reduction = "rpca", verbose = FALSE)
rm(list)
invisible(gc())
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = FALSE)
rm(anchors)
invisible(gc())
integrated <- RunPCA(integrated, verbose = FALSE)
integrated <- RunUMAP(integrated, dims = 1:30)
integrated <- FindNeighbors(object = integrated, dims = 1:30)
integrated <- FindClusters(object = integrated, resolution=0.2)
invisible(gc())
DimPlot(object = integrated, label=TRUE, pt.size = 1)
saveRDS(integrated, paste(outdir,"integrated/ctrl.rds", sep = "/"))
invisible(gc())

```



## Integration CTRL.BMP9 (A2, B2, C2, D2, E2)

```{r }

A2 <- readRDS(paste(data, "A2.rds", sep = "/"))
B2 <- readRDS(paste(data, "B2.rds", sep = "/"))
C2 <- readRDS(paste(data, "C2.rds", sep = "/"))
D2 <- readRDS(paste(data, "D2.rds", sep = "/"))
E2 <- readRDS(paste(data, "E2.rds", sep = "/"))
list <- c(A2, B2, C2, D2, E2)
rm(A2, B2, C2, D2, E2)
invisible(gc())

features <- SelectIntegrationFeatures(object.list = list, nfeatures = 3000)
list <- PrepSCTIntegration(object.list = list, anchor.features = features)
list <- lapply(X = list, FUN = RunPCA, verbose = FALSE, features = features)
anchors <- FindIntegrationAnchors(object.list = list, anchor.features = features, 
                                  normalization.method = "SCT", reduction = "rpca", verbose = FALSE)
rm(list)
invisible(gc())
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = FALSE)
rm(anchors)
invisible(gc())
integrated <- RunPCA(integrated, verbose = FALSE)
integrated <- RunUMAP(integrated, dims = 1:30)
integrated <- FindNeighbors(object = integrated, dims = 1:30)
integrated <- FindClusters(object = integrated, resolution = 0.2)
invisible(gc())
DimPlot(object = integrated, label=TRUE, pt.size = 1)
saveRDS(integrated, paste(outdir,"integrated/ctrl.bmp9.rds", sep = "/"))
invisible(gc())

```



## Integration HTAP (A3, B3, C3, D3, E3)

```{r }

A3 <- readRDS(paste(data, "A3.rds", sep = "/"))
B3 <- readRDS(paste(data, "B3.rds", sep = "/"))
C3 <- readRDS(paste(data, "C3.rds", sep = "/"))
D3 <- readRDS(paste(data, "D3.rds", sep = "/"))
E3 <- readRDS(paste(data, "E3.rds", sep = "/"))
list <- c(A3, B3, C3, D3, E3)
rm(A3, B3, C3, D3, E3)
invisible(gc())

features <- SelectIntegrationFeatures(object.list = list, nfeatures = 3000)
list <- PrepSCTIntegration(object.list = list, anchor.features = features)
list <- lapply(X = list, FUN = RunPCA, verbose = FALSE, features = features)
anchors <- FindIntegrationAnchors(object.list = list, anchor.features = features, 
                                  normalization.method = "SCT", reduction = "rpca", verbose = FALSE)
rm(list)
invisible(gc())
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = FALSE)
rm(anchors)
invisible(gc())
integrated <- RunPCA(integrated, verbose = FALSE)
integrated <- RunUMAP(integrated, dims = 1:30)
integrated <- FindNeighbors(object = integrated, dims = 1:30)
integrated <- FindClusters(object = integrated, resolution = 0.2)
invisible(gc())
DimPlot(object = integrated, label=TRUE, pt.size = 1)
saveRDS(integrated, paste(outdir,"integrated/htap.rds", sep = "/"))
invisible(gc())

```


## Integration HTAP.BMP9 (A4, B4, C4, D4, E4)

```{r }

A4 <- readRDS(paste(data, "A4.rds", sep = "/"))
B4 <- readRDS(paste(data, "B4.rds", sep = "/"))
C4 <- readRDS(paste(data, "C4.rds", sep = "/"))
D4 <- readRDS(paste(data, "D4.rds", sep = "/"))
E4 <- readRDS(paste(data, "E4.rds", sep = "/"))
list <- c(A4, B4, C4, D4, E4)
rm(A4, B4, C4, D4, E4)
invisible(gc())

features <- SelectIntegrationFeatures(object.list = list, nfeatures = 3000)
list <- PrepSCTIntegration(object.list = list, anchor.features = features)
list <- lapply(X = list, FUN = RunPCA, verbose = FALSE, features = features)
anchors <- FindIntegrationAnchors(object.list = list, anchor.features = features, 
                                  normalization.method = "SCT", reduction = "rpca", verbose = FALSE)
rm(list)
invisible(gc())
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = FALSE)
rm(anchors)
invisible(gc())
integrated <- RunPCA(integrated, verbose = FALSE)
integrated <- RunUMAP(integrated, dims = 1:30)
integrated <- FindNeighbors(object = integrated, dims = 1:30)
integrated <- FindClusters(object = integrated, resolution = 0.2)
invisible(gc())
DimPlot(object = integrated, label=TRUE, pt.size = 1)
saveRDS(integrated, paste(outdir,"integrated/htap.bmp9.rds", sep = "/"))
rm(integrated)
invisible(gc())

```

# Merge datasets

```{r}

ctrl <- readRDS(paste(outdir, "integrated/ctrl.rds", sep = "/"))
ctrl.bmp9 <- readRDS(paste(outdir, "integrated/ctrl.bmp9.rds", sep = "/"))
htap <- readRDS(paste(outdir, "integrated/htap.rds", sep = "/"))
htap.bmp9 <- readRDS(paste(outdir, "integrated/htap.bmp9.rds", sep = "/"))
list <- c(ctrl, ctrl.bmp9, htap, htap.bmp9)
rm(ctrl, ctrl.bmp9, htap, htap.bmp9)
merged <- Reduce(merge, list)
rm(list)
DefaultAssay(merged) <- "RNA"
merged <- FindVariableFeatures(merged, nfeatures = 3000)
merged <- ScaleData(merged)
merged <- RunPCA(merged)
merged <- RunUMAP(merged, dims = 1:30)
merged <- FindNeighbors(object = merged, dims = 1:30)
merged <- FindClusters(object = merged, resolution = 0.2)
invisible(gc())
DimPlot(merged, group.by = "seurat_clusters", label=TRUE, pt.size = 1)
DimPlot(merged, group.by = "phenotype", label=TRUE, pt.size = 1)
DimPlot(merged, group.by = "BMP9", label=TRUE, pt.size = 1)
saveRDS(merged, paste(outdir,"integrated/merged.rds", sep = "/"))

```


# Session Info

```{r sessinf}
sessionInfo()
```
