---
title: "10X HTAP NucSeq - Cell Proportions"
author: '[Yvon Mbouamboua](mbouamboua@ipmc.cnrs.fr)'
output:
  html_document:
    theme: united
    df_print: kable
  html_notebook:
    code_folding: none
    theme: united
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=TRUE, warning=FALSE}
# Chunck options
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, cache = FALSE, cache.lazy = FALSE, tidy = TRUE, message = FALSE, warning = FALSE)

# Define directories
work.dir <- "/data/data_mbouamboua/10x.htap/bmp9"
data.dir <- paste(work.dir, "outs", "rds", "v1", sep = "/")
output.dir <- paste(work.dir, "outs", sep = "/")

# Setting parameters
the.seed <- 1337L # Computational Parameters

## Memory 
options(future.globals.maxSize = 80000 * 1024^2)
```

# Setting seed and loading R packages

```{r seed_packages}
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(speckle))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(limma))
set.seed(the.seed)

```


# Cell proportions per sample


```{r fig.width=3, fig.height=4}
htap <- readRDS(paste(data.dir, "htap_without_cycling.rds", sep = "/"))
Seurat::Idents(htap) <- "ALK1"
sub <- subset(htap, idents = c("ALK1 hight", "ALK1 low"))
Seurat::Idents(sub) <- "condition"
sub <- subset(sub, idents = c("PAH", "CTRL"))
DimPlot(sub)
Seurat::Idents(sub) <- "ALK1"

myPalette <- list()
myPalette$sampleColor <- setNames(
colorRampPalette(RColorBrewer::brewer.pal(n = 11, name = 'RdBu'))(10),
  #viridis::viridis(14),
  c("H230", "H231","H247","H248","H250","C686518" ,"C681725", "C681086", "C685116", "C676136")
)

Idents(sub) <- "ALK1"
freq_table <- prop.table(x = t(table(sub@active.ident, sub@meta.data[, "sample"])), margin = 2)*100
freq_table <- reshape2::melt(freq_table)
freq_table <- freq_table[order(freq_table$Var1, decreasing = T),]

p <- ggplot(freq_table, aes(fill=Var1, y=value, x=Var2)) +
  geom_bar(position="stack", stat="identity", col="black", show.legend = T) +
  #scale_y_reverse() +
  #theme_bw() +
  #theme_void() +
  theme_classic() +
  labs(x=" ", y="nCells(%)", fill = "Samples") +
   guides(fill = guide_legend(reverse = TRUE)) +
  theme(axis.title = element_blank(),
        text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, 
                                   hjust = 0.5,
                                   vjust = 0.5,
                                   color = "black"),
        #axis.ticks.y = element_blank(),
        #axis.text.y = element_blank(),
        legend.key.size = unit(0.3, "cm")) +
  scale_fill_manual(values = myPalette$sampleColor) 

print(p)

pdf(paste(output.dir, "figures", "sample_proportion.pdf", sep = "/"), width = 3, height = 4, useDingbats = FALSE)
print(p)
dev.off()

```
